# Required
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: 3.9
  

# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: docs/conf.py

# Optionally set the version of Python and requirements required to build your docs
python:
   version: 3.9
   install:
   - requirements: requirements.docs.txt
   - requirements: requirements.txt
