name: cdlib
dependencies:
- python=3.9
- numpy
- matplotlib
- scikit-learn
- tqdm
- networkx>=3.0
- demon
- python-louvain
- nf1
- scipy
- pulp
- seaborn
- pandas
- eva_lcd
- bimlpa
- python-igraph
- angelcommunity
- pooch
- dynetx
- thresholdclustering
- python-Levenshtein
- plotly
