{% set name = "cdlib" %}
{% set version = "0.4.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"

requirements:
  host:
    - python=3.9
    - numpy
    - matplotlib
    - scikit-learn
    - tqdm
    - networkx>=3.0
    - demon
    - python-louvain
    - nf1
    - scipy
    - pulp
    - seaborn
    - pandas
    - eva_lcd
    - bimlpa
    - python-igraph
    - angelcommunity
    - pooch
    - dynetx
    - thresholdclustering
    - python-Levenshtein
    - setuptools
    - plotly
  build:
    - python
    - setuptools
  run:
    - python=3.9
    - numpy
    - matplotlib
    - scikit-learn
    - tqdm
    - networkx>=3.0
    - demon
    - python-louvain
    - nf1
    - scipy
    - pulp
    - seaborn
    - pandas
    - eva_lcd
    - bimlpa
    - python-igraph
    - angelcommunity
    - pooch
    - dynetx
    - thresholdclustering
    - python-Levenshtein
    - plotly

about:
  home: "https://github.com/GiulioRossetti/cdlib"
  license: "BSD"
  license_family: "BSD"
  license_file: ""
  summary: "Community Discovery Library"
  doc_url: "https://cdlib.readthedocs.io/"
  dev_url: "https://github.com/GiulioRossetti/cdlib"

extra:
  recipe-maintainers:
    - GiulioRossetti
